// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'pirate_quest';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String BOAT = 'assets/boat.png';
  static const String HAT = 'assets/hat.png';
  static const String HOPPIE = 'assets/hoppie.png';
  static const String MERLIN = 'assets/merlin.png';
  static const String MOKSH = 'assets/moksh.png';
}
